name: marketplace_analytics
version: '1.0.0'
config-version: 2
require-dbt-version: '>=2.0.0,<3.0.0'
profile: marketplace_analytics

models:
  marketplace_analytics:
    +materialized: view
    silver:
      +schema: silver
    gold:
      +schema: analytics

flags:
  send_anonymous_usage_stats: false
